version: '2.0'

services:
  authentication-service:
    container_name: authentication-service
    build:
      context: .
      dockerfile: Dockerfile
    image: vancheck-auth-service:latest
    command: ['npm', 'run', 'start:prod']
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      MODE: develop
      DATABASE_USER: vancheck
      DATABASE_PASSWORD: vancheck
      DATABASE_HOST: localhost
      DATABASE_PORT: 3306
      DATABASE_NAME: vancheck_authentication
      # SENTRY_DSN: https://9359ad78797547e3998c39dc43877e8e@o1397151.ingest.sentry.io/6722213
      KAFKA_BROKERS: '["localhost:29092"]'
    ports:
      - '8001:3000'